<?php
require('../vendor/fpdf/fpdf.php');
include '../conn.php';
include './check_session.php';

$volunteer_id = $_SESSION['user_id'];
$event_id = $_GET['event_id'] ?? null;

if (!$event_id) {
    die("No event ID provided.");
}

$stmt = $conn->prepare("
    SELECT 
        u.name AS volunteer_name, 
        e.title AS event_title, 
        e.date AS event_date, 
        a.name AS admin_name,
        o.name AS org_name
    FROM users u
    JOIN task_assignments ta ON ta.volunteer_id = u.id
    JOIN tasks t ON t.id = ta.task_id
    JOIN events e ON e.id = t.event_id
    JOIN users a ON a.id = e.created_by
    LEFT JOIN organizations o ON o.admin_id = e.created_by
    WHERE u.id = ? AND e.id = ?
    LIMIT 1
");
$stmt->bind_param("ii", $volunteer_id, $event_id);
$stmt->execute();
$result = $stmt->get_result();
$data = $result->fetch_assoc();
$stmt->close();

if (!$data) {
    die("You are not authorized or event not found.");
}

$volunteer_name = $data['volunteer_name'];
$event_title = $data['event_title'];
$event_date = date("F j, Y", strtotime($data['event_date']));
$organization_name = !empty($data['org_name']) ? $data['org_name'] : 'VolunteerHub';
$host_signature = $organization_name;

// ===================== CUSTOM PDF CLASS =====================
class PDF extends FPDF
{
    protected $angle = 0;

    function Header()
    {
        // 🎨 Faint patterned background (replace 'pattern.png' with your own image if available)
        if (file_exists('../assets/pattern.png')) {
            $this->Image('../assets/pattern.png', 0, 0, 297, 210); // light pattern background
        } else {
            // fallback color background if pattern not found
            $this->SetFillColor(250, 245, 235);
            $this->Rect(0, 0, 297, 210, 'F');
        }

        // 🟤 Border frame
        $this->SetDrawColor(160, 130, 100);
        $this->SetLineWidth(1.5);
        $this->Rect(10, 10, 277, 190);

        // 🏅 Title
        $this->SetFont('Arial', 'B', 26);
        $this->SetTextColor(80, 50, 30);
        $this->Cell(0, 20, 'Certificate of Acknowledgement', 0, 1, 'C');
        $this->Ln(10);
    }

    function Watermark($text)
    {
        $this->SetFont('Arial', 'B', 70);
        $this->SetTextColor(240, 240, 240);
        $this->Rotate(45, 100, 150);
        $this->Text(40, 150, $text);
        $this->Rotate(0);
    }

    function Rotate($angle, $x = -1, $y = -1)
    {
        if ($x == -1)
            $x = $this->x;
        if ($y == -1)
            $y = $this->y;
        if ($this->angle != 0)
            $this->_out('Q');
        $this->angle = $angle;
        if ($angle != 0) {
            $angle *= M_PI / 180;
            $c = cos($angle);
            $s = sin($angle);
            $cx = $x * $this->k;
            $cy = ($this->h - $y) * $this->k;
            $this->_out(sprintf(
                'q %.5F %.5F %.5F %.5F %.5F %.5F cm 1 0 0 1 %.5F %.5F cm',
                $c, $s, -$s, $c, $cx, $cy,
                -$cx, -$cy
            ));
        }
    }

    function Footer()
    {
        $this->SetY(-10);
        $this->SetFont('Arial', 'I', 10);
        $this->SetTextColor(120, 120, 120);
        $this->Cell(0, 10, 'Generated by VolunteerHub', 0, 0, 'C');
    }
}

ob_clean();

$pdf = new PDF('L', 'mm', 'A4'); // Landscape
$pdf->AddPage();

// 🌊 Watermark
$pdf->Watermark($organization_name);

// ====== Custom Fonts ======
$pdf->AddFont('Allura', '', 'Allura-Regular.php');

// ====== Volunteer Name ======
$pdf->SetFont('Allura', '', 60);
$pdf->SetTextColor(50, 20, 20);
$pdf->Ln(25);
$pdf->Cell(0, 20, $volunteer_name, 0, 1, 'C');
$pdf->Ln(10);

// ====== Certificate Text ======
$pdf->SetFont('Arial', '', 16);
$pdf->SetTextColor(60, 60, 60);
$pdf->Cell(0, 10, 'is hereby recognized for actively participating in the event', 0, 1, 'C');
$pdf->Ln(8);

// ====== Event Title ======
$pdf->SetFont('Arial', 'B', 20);
$pdf->SetTextColor(30, 30, 30);
$pdf->Cell(0, 12, '"' . $event_title . '"', 0, 1, 'C');
$pdf->Ln(8);

// ====== Date ======
$pdf->SetFont('Arial', '', 16);
$pdf->Cell(0, 10, 'held on ' . $event_date, 0, 1, 'C');
$pdf->Ln(20);

// ====== Organization Section ======
$pdf->SetFont('Arial', 'B', 18);
$pdf->SetTextColor(50, 30, 30);
$pdf->Cell(0, 10, $organization_name, 0, 1, 'C');
$pdf->Ln(5);

$pdf->SetFont('Arial', 'I', 14);
$pdf->Cell(0, 10, '(Signed by ' . $host_signature . ')', 0, 1, 'C');
$pdf->Ln(20);

// Decorative Line
$pdf->SetDrawColor(160, 130, 100);
$pdf->SetLineWidth(0.8);
$pdf->Line(90, 160, 200, 160);

$pdf->Output('I', 'Acknowledgement_' . $volunteer_name . '.pdf');
exit;
?>
